# This action scans by moving the head/camera for faces that are recognised
# There are no parameters to start the action
---
# Results of the final image/position scanned
face_recognition detected
---
# Percentage complete and result of the latest image/position scanned
float32 progress
face_recognition detected

